return function(map)
  map("n", "<leader>ha", "<cmd>lua require('harpoon.mark').add_file()<cr>", { desc = "add harpoon file" })
  map("n", "<leader>ht", "<cmd>lua require('harpoon.ui').toggle_quick_menu()<cr>", { desc = "harpoon ui" })
  map("n", "<leader>hh", "<cmd>lua require('harpoon.ui').nav_prev()<cr>", { desc = "Jump to previous" })
  map("n", "<leader>hl", "<cmd>lua require('harpoon.ui').nav_next()<cr>", { desc = "Jump to next" })
  map("n", "<leader>h+", "<cmd>lua require('harpoon.ui').nav_file(1)<cr>", { desc = "Jump to 1" })
  map("n", "<leader>h[", "<cmd>lua require('harpoon.ui').nav_file(2)<cr>", { desc = "Jump to 2" })
  map("n", "<leader>h{", "<cmd>lua require('harpoon.ui').nav_file(3)<cr>", { desc = "Jump to 3" })
  map("n", "<leader>h(", "<cmd>lua require('harpoon.ui').nav_file(4)<cr>", { desc = "Jump to 4" })
  map("n", "<leader>h#", "<cmd>lua require('harpoon.ui').nav_file(5)<cr>", { desc = "Jump to 5" })
  map("n", "<leader>h=", "<cmd>lua require('harpoon.ui').nav_file(6)<cr>", { desc = "Jump to 6" })
  map("n", "<leader>h)", "<cmd>lua require('harpoon.ui').nav_file(7)<cr>", { desc = "Jump to 7" })
  map("n", "<leader>h}", "<cmd>lua require('harpoon.ui').nav_file(8)<cr>", { desc = "Jump to 8" })
  map("n", "<leader>h]", "<cmd>lua require('harpoon.ui').nav_file(9)<cr>", { desc = "Jump to 9" })
  map("n", "<leader>h*", "<cmd>lua require('harpoon.ui').nav_file(10)<cr>", { desc = "Jump to 10" })
end
